name: CI - Cypress Tests
on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      petstore:
        image: swaggerapi/petstore3:unstable
        ports:
          - 8080:8080
        options: >-
          --name swaggerapi-petstore3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Wait for Petstore API
        run: |
          for i in {1..30}; do
            if nc -z localhost 8080; then
              echo "Petstore API is up!"
              exit 0
            fi
            echo "Waiting for Petstore API..."
            sleep 2
          done
          echo "Petstore API did not start in time!" && exit 1
        shell: bash

      - name: Run Cypress tests (all)
        run: npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/reports,overwrite=true,html=true,json=false"

      - name: Generate Mochawesome HTML report
        run: |
          npx mochawesome-merge cypress/reports/*.json | npx mochawesome-report-generator --reportDir cypress/reports --reportFilename mochawesome.html

      - name: Upload Mochawesome HTML report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-html-report
          path: cypress/reports/mochawesome.html

      - name: Upload Cypress videos (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/

      - name: Upload Cypress screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
