name: CI - Cypress Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      petstore:
        image: swaggerapi/petstore3:unstable
        ports:
          - 8080:8080
        options: >-
          --name swaggerapi-petstore3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./my-cypress-project

      - name: Wait for Petstore API
        run: |
          for i in {1..30}; do
            if nc -z localhost 8080; then
              echo "Petstore API is up!"
              exit 0
            fi
            echo "Waiting for Petstore API..."
            sleep 2
          done
          echo "Petstore API did not start in time!" && exit 1
        shell: bash

      - name: Run Cypress tests (all)
        run: npx cypress run
        working-directory: ./my-cypress-project

      - name: Upload Cypress videos (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: my-cypress-project/cypress/videos/

      - name: Upload Cypress screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: my-cypress-project/cypress/screenshots/
